In [5]:
#standardisation 
import numpy as np 
x=np.array([0,1,2,3,4,5])
mean_x=np.mean(x)
std_x=np.std(x)
new_x=(x-mean_x)/std_x
new_x

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [6]:
np.mean(new_x)

-3.700743415417188e-17

In [7]:
np.std(new_x)

1.0

In [8]:
#normalisation 
norm_x=(x-np.min(x))/(np.max(x)-np.min(x))
norm_x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
#standardisation 
x1=[[0],[1],[2],[3],[4],[5]]
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
new_x=sc.fit_transform(x1)
new_x

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])

In [9]:
#standardisation by sklearn   
x1=([[0],[1],[2],[3],[4],[5]])

In [10]:
x1

[[0], [1], [2], [3], [4], [5]]

In [11]:

from sklearn.preprocessing import StandardScaler

In [12]:
sc=StandardScaler()


In [13]:
new_x1=sc.fit_transform(x1)
new_x1

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])

In [14]:
norm_x=(x-np.min(x))/(np.max(x)-np.min(x))
norm_x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
norm=MinMaxScaler()

In [17]:
norm_x1=norm.fit_transform(x1)
norm_x1

array([[0. ],
       [0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ]])

In [18]:
from sklearn.datasets import load_iris 
dataset=load_iris()

In [19]:
data=dataset.data
target=dataset.target

In [20]:
data.shape

(150, 4)

In [21]:
target.shape

(150,)

In [22]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.3)

In [26]:
x_train.shape

(105, 4)

In [27]:
x_test.shape

(45, 4)

In [28]:
y_train.shape

(105,)

In [29]:
y_test.shape

(45,)